### PR TITLE
Add javascript highlighting

### PR DESCRIPTION
**Pull request by jamestalmage**
This adds javascript highlighting to the editor, but is probably not an ideal long term solution for supporting the full range of GH languages. I have not verified, but I imaging loading up every supported language would be slow.

Ideally, we would submit a PR to Codemirror that allowed for async loading of language support as specific fenced code blocks were detected, but looking at the code, that might be a pretty big undertaking. The alternative would be a simple hack that detected a failed load, loaded it async, then refreshed the rendering (might be much more doable).

Alternatively, we could create an options page where users were presented with a list of their most used languages, and placed checkboxes next to them.

In either case, we probably need to look into browserify partitioning: https://github.com/substack/browserify-handbook#partitioning

### CODE REVIEW

**Comment by DrewML** [comment]
@jamestalmage Nice! I didn't realize that CodeMirror would support syntax highlighting _in_ the fences (which I was super bummed about).

With regards to languages other than JavaScript, I'm a bit on the fence about whether async loading would even be necessary. Chrome loads all files related to the extension from the cache, so the download cost would only be incurred the first time a user downloads the extension (which would be the case even if we lazy-loaded).

I'll run a test later with some more languages bundled and see if there is any noticeable performance impact.

Thanks for this PR!

**Comment by jamestalmage** [comment]
> Chrome loads all files related to the extension from the cache, so the download cost would only be incurred the first time a user downloads the extension (which would be the case even if we lazy-loaded).

To be clear, I am suggesting shipping _all_ supported languages with the extension. Who cares how big the extension download is. We could just try to require all of them and see what it does to performance. If it's detrimental, then explore chunking them.

**Comment by DrewML** [comment]
👍 Sounds like we're on the same page

**Comment by jamestalmage** [comment]
I meant to say "let's ship them all", but the word "not" slipped in there. Do we still agree?

As for performance, I think loading them all is probably going to be problematic. Looking at [the GFM demo](https://codemirror.net/mode/gfm/index.html), it feels pretty snappy. However, while it appears `java` and `javascript` are both enabled, it seems `haskell` and `jade` are not. I think they picked a few of the most popular languages to improve performance (though it might just be an effort to save bandwidth).

**Comment by DrewML** [comment]
> I meant to say "let's ship them all", but the word "not" slipped in there. Do we still agree?

Yeah. For some weird reason, I read it without the "not" anyway :) My preference is definitely to load them all - if not, it will inevitably lead to feature requests and 1-off PR's for languages from new users.

**Comment by DrewML** [comment]
asdds

**Pull request merged**
